app/components/navbar/index.tsx
app/components/navbar/style.tsx
app/components/styledRegistry/index.tsx
app/layout.tsx
next.config.mjs
package.json
yarn.lock

Setup styled components
Setup styled component and add navbar component

Setup styled component and add navbar component

---

app/components/avtar/Avtar.tsx
app/components/inboxCard/inboxCard.tsx
app/components/inboxCard/style.tsx
app/components/navbar/style.tsx
app/helpers/common.tsx
app/inbox/index.tsx
app/inbox/style.tsx
app/page.tsx
app/styles/colors.tsx

Create inbox screen design
Make design for inbox screen 
Make avtar component
make inbox card component

create inbox screen design

---

services/membership/signin.ts

Added services for singin flow.
Implemented a service `signInWithCode(email, code)` which can be used client side to singin user and create auth token using NextAuth's Credentials Provider.

added service to signin client side

---

app/inbox/page.tsx
components/styledRegistry/index.tsx
package.json
stores/index.ts
stores/userStore.ts
stores/workspaceStore.ts
yarn.lock

Setup mobx
Setup mobx folder structure

Setup mobx folder structure

---

app/details/page.tsx
app/details/style.tsx
app/login/page.tsx
app/onbording/page.tsx
app/onbording/style.tsx
assets/icons/SVGIcon.tsx
components/button/button.tsx
components/button/style.tsx
components/dropDown/dropDown.tsx
components/dropDown/style.tsx
components/input/input.tsx
components/input/style.tsx
components/profileSection/recentEvent.tsx
components/profileSection/styles.tsx
helpers/common.tsx
helpers/raw.tsx
styles/colors.tsx

Onboarding step 1 & 2 screens design
created Onboarding step 1 & 2 screens design

Onboarding step 1 & 2 screens design

---

prisma/schema.prisma
services/membership/signup.ts

Implemented Services to create workspace.
Created a service which can be used to create a workspace on database.

implemented services to create workspace

---

app/details/page.tsx
app/onbording/page.tsx
app/onbording/style.tsx
components/dropDown/dropDown.tsx
components/dropDown/style.tsx
components/tag/styles.tsx
components/tag/tag.tsx
helpers/raw.tsx

Fix drop down jerk issue and remove select default color
Fix drop down jerk issue and remove select default color

Fix drop down jerk issue

---

prisma/schema.prisma
services/membership/signup.ts
services/workspace.ts

Implemented services to invite users to workspace.
Added `InvitedUsers` collection which track invited users and when these users sign-ups they are automatically added to invited workspace, While verified users are directly added to workspace when invited.

implemented services for inviting users

---

app/api/auth/signup/route.ts
app/login/login.tsx
app/signup/page.tsx
app/signup/style.tsx
services/clientSide/authService.ts
services/serverSide/workspace.ts

Implemented User Signup flow.
User first enters email address and user name, then user is sent verification code and an unverified account is created.
After that user enters the verification code which is verified by next-auth services and on successful auth, an verified account is created and user is forwarded to onboarding page.

implement signup functionality

---

prisma/schema.prisma

Updated ticket and message schemas.
Added required fields and enums in ticket and message schema.

update tickets and messages schema

---

app/login/login.tsx
middlewares/withAuth.ts
middlewares/withWorkspaceAuth.ts
services/serverSide/workspace.ts

Implemented auth middlewares for protecting api routes.
Implemeneted 2 middlewares:
- withAuth: Checks if user is logged-in.
- withWorkspaceAuth: Checks if user is logged-in and present in current workspace.

implemented auth middlewares

---

app/login/login.tsx
app/signup/signup.tsx

Replaced getServerSession with useSession in client components to improve performance.

replaced getServerSession with useSession

---

app/api/auth/login/route.ts
app/api/auth/sendVerificationCode/route.ts
app/api/auth/signup/route.ts
global/errorMessages.ts
helpers/errorHandler.ts
lib/zod.ts
package.json
yarn.lock

Implemented zod and schema to validate request bodies.
`emailSchema`: validate email input.
`displayNameSchema`: validate user's name input.
`nameSchema`: validate generic name input.
`profilePicSchema`: validate image's url input.

implemented zod and schemas

---

.husky/pre-commit

husky setup
set up husky for not pushing code direct in main or dev

husky setup

---

app/details/page.tsx
app/onboarding/onboarding.tsx
app/onboarding/style.tsx
components/dropDownWithTag/dropDownWithTag.tsx
components/dropDownWithTag/style.tsx

Combine drop down and tag
Created new component where tag and drop down are being combine

Combine drop down and tag

---

.vscode/settings.json
prisma/schema.prisma

Formatted Ticket and message schemas to store reference IDs of emails.

changed ticket and message schemas

---

app/api/tickets/route.ts
prisma/schema.prisma
services/serverSide/ticket.ts

Implemeted Services to create/fetch tickets of a workspace
`GET`: /api/tickets
returns array of tickets of `workspace_id` provided in auth header

implemeted services to create and fetch tickets

---

app/api/tickets/[ticketId]/messages/route.ts
middlewares/withWorkspaceAuth.ts
prisma/schema.prisma
services/serverSide/message.ts

Implement services to create & fetch messages of a ticket.
GET: `/api/ticket/[ticketId]/messages`
returns all messages of a ticket

implement services to create/fetch message of ticket

---

app/login/login.tsx
app/signup/signup.tsx
helpers/appInitHelper.tsx
services/clientSide/authService.ts
services/clientSide/workspace.ts
services/serverSide/membership/signup.ts

App init - set condition for organization status check and set current organization in mobx
App init helper - check workspace status and details check
https://share.teamcamp.app/JRjDwLA72BWJP3MFmh3IY

App init helper - check workspace status and details check

---

app/api/webhooks/postmark/route.ts
prisma/schema.prisma
services/serverSide/message.ts
services/serverSide/ticket.ts
utils/dataTypes.tsx

Implemented webhook for postmark which forwards the incoming emails to tickets.
POST: `/api/webhooks/postmark`
Will forward the incoming email to tickets.

implemented webhook for tickets

---

app/inbox/page.tsx
app/login/login.tsx
components/avtar/Avtar.tsx
components/inboxCard/inboxCard.tsx
global/constants.ts
helpers/common.tsx
services/clientSide/ticketServices.ts
stores/index.ts
stores/ticketStore.ts
stores/workspaceStore.ts

Inbox -> make this list dynamic.
Inbox - make tickets list dynamic

Inbox - make tickets list dynamic

---

services/clientSide/authService.ts
stores/userStore.ts

Implemented service to logout from current session.
When logout service is called:
- Clear session and cookies data
- Clear UserDetails from user mobx reducer.

implemented service to logout

---

app/inbox/page.tsx
components/dropDown/style.tsx
components/inboxCard/inboxCard.tsx

Create drop down in inbox same as ticket details
Create drop down in inbox same as ticket details

fix drop down scroll issue

---

prisma/schema/enums.prisma
prisma/schema/relations.prisma
prisma/schema/schema.prisma

Implement schemas fot ticket labels
Added a `Label` entity with realtions:
Worspace (one to many) labels (many to many) tickets.

updated schema for ticket labels

---

components/navbar/profileDropdown.tsx
services/clientSide/authService.ts

User - Logout working
User - Logout working
After logout navigate to login screen

User - Logout working

---

app/api/tickets/[ticketId]/messages/route.ts
app/api/tickets/[ticketId]/route.ts
app/api/tickets/route.ts
app/api/workspaces/inviteUsers/route.ts
middlewares/withWorkspaceAuth.ts
prisma/schema/schema.prisma
services/serverSide/ticket.ts
services/serverSide/workspace.ts

Optimized withWorkspaceAuth middleware.
Removed unnessary fields of workspace during auth.
Updated API routes with this new optimized middleware.

optimized withWorkspaceAuth

---

app/api/tickets/[ticketId]/labels/[labelId]/route.ts
app/api/tickets/[ticketId]/labels/route.ts
app/api/tickets/[ticketId]/route.ts
app/api/workspaces/labels/[labelId]/route.ts
app/api/workspaces/labels/route.ts
helpers/common.tsx
lib/zod/label.ts
lib/zod/ticket.ts
services/serverSide/label.ts
services/serverSide/ticket.ts

Implemented services and APIs to create/update/delete ticket labels of a workspace.
POST: `/api/workspaces/labels` (Create a label for the workspace)
```ts
{
"name": "Label name",
"icon": "Icon name",
"color"?: "label color"
}
```
PUT: `/api/workspaces/labels/[labelId]` (Update label of a workspace)
```ts
{
"name": "Label name",
"icon": "Icon name",
"color"?: "label color"
}
```
DELETE: `/api/workspaces/labels/[labelId]` (Delete a label of a workspace)
GET: `/api/tickets/[ticketId]/labels` (Get labels list of the ticket)
POST: `/api/tickets/[ticketId]/labels/[labelId]` (Assign a label to the ticket)
DELETE:  `/api/tickets/[ticketId]/labels/[labelId]` (Remove a label from the ticket)

implemented services and APIs for ticket labels

---

app/contact/page.tsx
app/details/[ticket_id]/ticketDetails.tsx
app/inbox/page.tsx
app/inbox/style.tsx
components/appProvider/index.tsx
components/inboxCard/style.tsx
components/navbar/navbar.tsx
components/navbar/profileDropdown.tsx
components/navbar/style.tsx
components/profileSection/styles.tsx
global/constants.ts

Add navbar component in App provider
Add navbar component in App provider and remove all file navbar

navbar component use in App provider

---

app/setting/style.tsx
components/dropDown/style.tsx
components/navbar/profileDropdown.tsx

Fix shadow issue in setting screen
Fix shadow issue

fix shadow issue in setting screen

---

app/setting/myprofile/page.tsx
app/setting/style.tsx
components/input/input.tsx
components/navbar/navbar.tsx
components/settingAppProvider/index.tsx
components/settingNavBar/style.tsx

Update spacing in setting page
Update spacing in setting page, fix profile pop up click issue, fix input type issue in my profile screen

update spacing in setting page

---

package.json
prisma/schema/schema.prisma
services/serverSide/contact.ts
services/serverSide/ticket.ts
yarn.lock

Implemented services for Contact' details.
Updated ticket's services such that it creates or links exisiting contact details to the ticket.

Added Contact services and updated ticket services

---

components/inboxCard/inboxCard.tsx
components/profileSection/profileSection.tsx

Fix changes for ticket data change
Fix changes for ticket data change

Fix build issue changed for ticket data structure change

---

app/api/tickets/[ticketId]/route.ts
lib/zod/ticket.ts
services/serverSide/ticket.ts

Removed senderName and senderEmail from update ticket APIs, since its managed by Contact now.

removed senderName and senderEmail from update Ticket API

---

components/inboxCard/inboxCard.tsx
components/profileSection/profileSection.tsx
stores/ticketStore.ts
utils/appTypes.tsx

Fix use of sender details from contact
Fix use of sender details from contact

Fix use of sender details from contact

---

app/api/webhooks/postmark/route.ts
helpers/environment.ts
services/serverSide/workspace.ts

Updated webhook logic such that incoming emails to `{workspaceId}@inbound.getconnect.app` will be forwarded to workspace with `workspaceId`.

updated postmark webhook

---

app/details/[ticket_id]/ticketDetails.tsx
app/details/style.tsx
assets/icons/SVGIcon.tsx
components/settingNavBar/settingNavBar.tsx

created close and snooze button in header
created close and snooze tag in header and also changed the workSpace to workspace in settings navbar.

created close and snooze button in header

---

helpers/common.tsx
services/clientSide/authService.ts
services/clientSide/ticketServices.ts
services/clientSide/workspace.ts

Show the same error in the alert which come from api
Show proper error get from API response

Show proper error get from API response

---

components/settingNavBar/style.tsx

fixed spacing issue in setting screen
fixed spacing issue for setting screen in settingNavbar

fixed spacing issue in setting screen

---

app/contact/style.tsx
app/details/[ticket_id]/ticketDetails.tsx
app/details/style.tsx
app/inbox/style.tsx
components/inboxCard/inboxCard.tsx
components/inboxCard/style.tsx
components/messageCard/style.tsx

Inbox - change card structure
Inbox - change card structure

change inbox card structure

---

assets/icons/SVGIcon.tsx
components/inboxCard/inboxCard.tsx
components/inboxCard/style.tsx

added action button on hover for ticket card
in inbox added action button on hover of ticket card.

added action button on hover for ticket card

---

app/api/workspaces/route.ts
app/api/workspaces/users/[userId]/route.ts
lib/zod/workspace.ts
middlewares/withAdminAuth.ts
prisma/schema/enums.prisma
prisma/schema/relations.prisma
services/serverSide/workspace.ts

Implemented services and APIs to remove user from workspace and change role of user in the workspace.
Added `role` field in UserWorkspace relationship.

implemented services and APIs to remove member and update user role

---

app/details/[ticket_id]/ticketDetails.tsx
components/dropDown/dropDown.tsx
components/inboxCard/inboxCard.tsx
services/serverSide/workspace.ts

assign user list show dynamic in dropdown
assign user list show dynamic in dropdown
https://share.teamcamp.app/3A28PFp0ngAjUwUCCvSUc

assign user list show dynamic in dropdown

---

app/api/user/route.ts
services/serverSide/user.ts

Implemented Services and API route to update user info.
PUT: `api/user`
```js
{
displayName: "new name",
profilePic: "new profile Pic"
}
```

implemented services and API to update user info

---

app/details/[ticket_id]/ticketDetails.tsx
app/details/style.tsx
components/dropDownWithTag/dropDownWithTag.tsx
components/profileSection/profileSection.tsx
components/profileSection/styles.tsx
components/profileSection/workDetails.tsx

Ticket details -> update profile section design in sidebar
update profile section design in ticket details and make snooze dropdown

ticket details - update user profile in sidebar

---

components/dropDown/style.tsx

Fix assign drop down design issue
Fix assign drop down design issue

fix drop down design issue

---

app/api/user/route.ts
services/serverSide/user.ts

Implemented services and API route to get current user.
GET: `/api/user`

implement service and API to get current user

---

app/setting/members/page.tsx
utils/dataTypes.tsx

Make member-list dynamic
get workspace Data, from this data display member of workspace

display workspace member dynamically

---

app/api/workspaces/route.ts
lib/zod/common.ts
prisma/schema/schema.prisma
services/serverSide/workspace.ts

Implemented services and API route to update Workspace
PUT: `/api/workspaces`
```json
{
"name": "New workspace name",
"imageUrl": "new image url"
}
```

implemented services and API to update workspace

---

components/contextMenu/contextMenu.tsx
components/contextMenu/style.tsx

fixed the context menu position
fixed the context menu position when the dropdown open

fixed the context menu position

---

components/contextMenu/contextMenu.tsx
components/contextMenu/style.tsx

Add 'Close' option in context menu
Add 'Mark ad one' option in context menu

add mark as done option in context menu

---

components/inviteMemberModal/inviteMemberModal.tsx
components/inviteMemberModal/style.tsx
services/clientSide/workspaceServices.ts
stores/workspaceStore.ts
utils/dataTypes.tsx

Make invite member working
create action updateInviteModalInput in workspaceStore and use in InviteMemberModal component
https://share.teamcamp.app/wJdw_FbV7aSNmn_RyQxZK

create invite member functionality

---

app/selectworkspace/page.tsx
app/selectworkspace/selectWorkspace.tsx
app/selectworkspace/style.tsx
app/setting/workspaceprofile/page.tsx
app/setting/workspaceprofile/workSpaceProfile.tsx
components/button/style.tsx
components/navbar/profileDropdown.tsx
components/workspaceCard/workspaceCard.tsx
styles/colors.tsx

Create design for workspace flow
Create design for workspace flow

Create design for workspace flow

---

app/setting/members/page.tsx
components/dropDown/dropDown.tsx
components/memberCard/memberCard.tsx
services/clientSide/workspaceServices.ts
utils/appTypes.tsx

Make add admin working
create makeAdmin function and call this function in dropDown component
https://share.teamcamp.app/pI53BeP9ZNttI5RK5v927

make add admin working

---

app/api/workspaces/[workspaceId]/route.ts
services/serverSide/workspace.ts

Added `role` field in worksapce's users list.
Implemente API route to fetch workspace by ID.
GET: `/api/workspaces/{workspaceID}`
Returns workspace object with all workspace details

Added user role in workspace user list and implemented API to fetch workspace by ID

---

app/inbox/inbox.tsx
components/inboxLoading/inboxLoading.tsx
components/inboxLoading/style.tsx

Create loading state design in inbox screen
Create loading state design in inbox screen

create loading state design in inbox

---

app/setting/myprofile/page.tsx
app/setting/style.tsx
components/button/button.tsx
helpers/common.tsx
services/clientSide/userService.ts
services/serverSide/user.ts

set profile image dynamic
set profile image dynamic
https://share.teamcamp.app/NIqwSVnlYHaIAzpQ-2FJc

set profile image dynamic

---

app/setting/myprofile/page.tsx

Setting - profile - hide phone number for now
Setting - profile - hide phone number for now

Setting - profile - hide phone number for now

---

components/appProvider/index.tsx
components/settingAppProvider/index.tsx

Fix hydration issue for settings pages
Fix hydration issue for settings pages
Works properly

Setting pages - fix hydration issue

---

app/api/workspaces/[workspaceId]/route.ts
middlewares/withAuth.ts
services/clientSide/workspaceServices.ts

Update auth method for get workspace details
Update auth method for get workspace details
Works properly

Update auth method for get workspace details

---

app/inbox/inbox.tsx

Fix context menu open issue
Ticket details - fix context menu open issue

fix context menu open issue

---

app/setting/members/page.tsx

after set admin changes not done in list
after set admin changes not done in list
https://share.teamcamp.app/8js_xUSSneoLsIM0qNqOy

after set admin changes done in list

---

app/contact/contact.tsx
app/contact/page.tsx
app/contact/style.tsx
app/details/[ticket_id]/ticketDetails.tsx
app/details/style.tsx
app/inbox/inbox.tsx
app/inbox/style.tsx
components/commentBox/style.tsx

same width inbox card and contact card
Same width inbox card and contact card and fix same margin and padding issue in ticket details

same width inbox card and contact card

---

app/details/[ticket_id]/ticketDetails.tsx
components/commentBox/index.tsx

Message box - make mention user working
Message box - make mention user working

Message box - make mention user working

---

prisma/schema/relations.prisma
services/serverSide/workspace.ts

Fixed multi relations in relation table.
Dropped `id` column and added composite primary key using primary keys of tables in relation.

updated relation schemas and related services

---

app/setting/members/page.tsx
services/clientSide/workspaceServices.ts
stores/workspaceStore.ts
utils/dataTypes.tsx

show invited users in list
show invited users in list

show invited users in list with Pending status

---

components/dropDown/dropDown.tsx

Inbox - assign box - make search functionality
Inbox - assign box - make search functionality
https://share.teamcamp.app/0ffPvh15gQ8daXLQbKnmn

Inbox - assign box - make search functionality

---

services/serverSide/ticket.ts

Implemented seprate service to update ticket's priority.
Add `updatePriority` in ticket services to update ticket's status to one of `"NONE" | "LOW" | "MEDIUM" | "HIGH" | "URGENT"`

added service to update ticket priority

---

helpers/emails.tsx

Implemented service to send email as reply.

implemented service to send email as reply

---

app/api/workspaces/[workspaceId]/route.ts
services/serverSide/workspace.ts

Modified workspace service to return current user's role in workspace object.

add current user role in workspace object

---

app/api/tickets/[ticketId]/changePriority/route.ts

Implemented API route to update ticket's priority levels.
PUT: `api/tickets/[ticketId]/changePriority`
```json
{
"priority": "LOW"
}
```

added API route to update ticket's priority

---

app/selectworkspace/selectWorkspace.tsx
services/clientSide/workspaceServices.ts
stores/workspaceStore.ts

show workspace list dynamic
show workspace list dynamic

 show workspace list dynamic

---

app/details/[ticket_id]/ticketDetails.tsx
components/contextMenu/contextMenu.tsx
components/inboxCard/inboxCard.tsx
services/clientSide/ticketServices.ts

update ticket priority services
update ticket priority services
https://share.teamcamp.app/uzA3hjn2f2BYvL72dsKvq

update ticket priority services

---

app/api/tickets/[ticketId]/changePriority/route.ts
app/api/webhooks/postmark/route.ts
prisma/schema/enums.prisma
prisma/schema/schema.prisma
services/serverSide/message.ts

Implemeted message events for change ticket's priortity, status, assignee and labels.
Modified message types and respective_id will be set.
Modified getMessage service to fetch respective data (assingee, label) by refrence id.

implement message event for change priority, status, assignee and label

---

services/clientSide/ticketServices.ts

create service for get messages for ticket
create service for get messages for ticket

create service for get messages for ticket

---

app/details/[ticket_id]/ticketDetails.tsx
components/AssigneeDropdown/dropDownWithTag.tsx
components/AssigneeDropdown/style.tsx
components/inboxCard/inboxCard.tsx

Ticket - show unassigned when there are no assignee for assign dropdown
Assignee dropdown - create separate dropdown for assignee and show unassignee if assignee not selected

Assignee dropdown - create separate dropdown for assignee

---

app/api/tickets/[ticketId]/changeAssignee/route.ts
services/serverSide/ticket.ts

Implemented API route to update ticket's assignee.
PUT: `/api/tickets/[ticketId]/changeAssignee`
```json
{
"assignee": "Assigned userId"
}
```

implement API to update ticket assignee

---

app/api/workspaces/inviteUsers/[userId]/route.ts
services/serverSide/workspace.ts

Implement API to remove invited user from a workspace
DELETE: `/api/workspaces/inviteUsers/[userId]`

implement API to remove invited user

---

app/contact/style.tsx
app/details/style.tsx
components/contactUsModal/contactUsModal.tsx
components/contactUsModal/style.tsx

Fix jerk issue in contact us modal
fixed the jerk issue in contact us modal with scrolling issue
https://share.teamcamp.app/MtDID2xmuQgWeKMhujXDu

Fix jerk issue in contact us modal

---

app/api/tickets/[ticketId]/changeStatus/route.ts
services/serverSide/ticket.ts

Implement service and API rotue to update ticket status.
PUT: `/api/tickets/[ticketId]/changeStatus`
```json
{
"status": "CLOSED"
}
```

implement API to change ticket status

---

app/api/tickets/[ticketId]/messages/route.ts
lib/zod/message.ts

Implement API to post regaular messages on ticket
POST: `/api/tickets/[ticketId]/messages`
```json
{
"content": "Message content",
"type": "REGULAR"
}
```

implement API to post regular message on tickets

---

app/details/[ticket_id]/ticketDetails.tsx
components/inboxCard/inboxCard.tsx
services/clientSide/ticketServices.ts

create client side service to update status
create client side service to update status

create client side service to update ticket status

---

services/clientSide/workspaceServices.ts

Create service to remove invited user
Create service to remove invited user

Create service to remove invited user

---

prisma/schema/relations.prisma
services/serverSide/message.ts
services/serverSide/workspace.ts

fixed messages order in ticket

---

assets/icons/SVGIcon.tsx
components/emailChannelCard/emailChannelCard.tsx
components/emailChannelCard/style.tsx
components/messageCard/style.tsx
styles/colors.tsx

Update email channel screen design
Update all font size, font color, update spacing

Update email channel design

---

app/details/[ticket_id]/ticketDetails.tsx
components/contextMenu/contextMenu.tsx
components/inboxCard/inboxCard.tsx
services/clientSide/ticketServices.ts

Create client side service to update assignee in ticket
Create client side service to update assignee

Create client side service to update assignee

---

services/clientSide/ticketServices.ts

Ticket - Create client side service for send message
Create client side service for send message

create client side service for send message

---

app/api/tickets/[ticketId]/route.ts
app/api/tickets/route.ts
lib/zod/common.ts
services/serverSide/ticket.ts

Modified ticket service to fetch tickets based on last updated time.
if `last_updated` field is passed in headers with valid datetime then only tickets whose `updated_at` is greater then `last_updated` time.

fixed typos and fetch tickets based on last updated time

---

app/api/tickets/[ticketId]/route.ts
app/api/tickets/route.ts
helpers/emails.tsx
lib/zod/common.ts
prisma/schema/schema.prisma
services/serverSide/ticket.ts

Implemented separate subject field in ticket for sending emails as reply.

Implement separate subject field for emails

---

app/api/tickets/[ticketId]/route.ts
app/api/tickets/route.ts
helpers/emails.tsx
lib/zod/common.ts
prisma/schema/schema.prisma
services/clientSide/ticketServices.ts
services/serverSide/ticket.ts
services/serverSide/workspace.ts

Modified workspace services such that, only workspace data is fetched while fetching workspace list of a user.
Removed users list from workspace object.

removed users list from workspace list

---

app/api/tickets/route.ts

Fixed ticket last updated bug.

Fix ticket last updated time bug

---

components/AssigneeDropdown/dropDownWithTag.tsx
components/inboxLoading/style.tsx
components/tag/tag.tsx

Ticket list - unassigned state design
Ticker list - unassigned state design

ticket list - unassigned state design

---

app/details/[ticket_id]/ticketDetails.tsx

Ticket details - show status change message activity
create switch case CHANGE_STATUS

Origin/ticket details/show status change message activity

---

prisma/schema/schema.prisma

Implemented Schema for API Keys.

implemented schema of API keys

---

middlewares/withAdminAuth.ts
middlewares/withAuth.ts
middlewares/withWorkspaceAuth.ts
services/serverSide/apiKey.ts
services/serverSide/workspace.ts

Modified auth middleware to utilize API keys.
If `API_KEY` auth header is passed with valid Key, then it will treat it as a session object.

Modify auth middlewares to utlizie api keys

---

services/serverSide/apiKey.ts

Implement service to get user and workspace details from api key.

implement service to get api details

---

app/details/[ticket_id]/ticketDetails.tsx

Ticket details - show re-open button
Restructure handleTicketStatus function

Origin/ticket details/show re open button

---

components/input/input.tsx
components/input/style.tsx
components/labelCard/labelCard.tsx
components/macroCard/macroCard.tsx
components/macroModal/macroModal.tsx
components/macroModal/style.tsx
components/messageCard/style.tsx

Update input component
Update input component and fix macros modal placeholder issue, fix edit label modal issue, and use input variant

update input component

---

components/messageCard/style.tsx
components/profileSection/styles.tsx

Ticket details -> width should be full width if content less
Content is show in full width and change ai block font style

ticket details - content is full width

---

middlewares/withAdminAuth.ts
middlewares/withAuth.ts
middlewares/withWorkspaceAuth.ts

fixed typo for API header

---

app/details/[ticket_id]/ticketDetails.tsx

Ticket details - comment box - show current user's profile
show current user's profile

Origin/comment box show current user's profile

---

app/details/[ticket_id]/ticketDetails.tsx

Ticket details - make message for email dynamic
Ticket details - make message for email dynamic

Ticket details - make message for email dynamic

---

components/datePicker/datePicker.tsx
components/questionCard/style.tsx

Ticket details -> Fix design for internal message
Ticket details -> Fix design for internal message

ticket details -> fix design for internal message

---

components/appProvider/index.tsx
helpers/appInitHelper.tsx
services/clientSide/workspaceServices.ts

App init - Select workspace option
set condition for Select workspace option

implement select workspace option

---

app/setting/members/members.tsx
components/inviteMemberModal/inviteMemberModal.tsx
components/modalComponent/modalComponent.tsx

Settings - member load data issue and invite issue
Settings - member load data issue and invite issue

Settings - member load data issue and invite issue

---

app/details/[ticket_id]/ticketDetails.tsx
app/details/style.tsx
components/internalMessageCard/internalMessageCard.tsx
components/internalMessageCard/style.tsx
components/messageCard/style.tsx

Ticket details - fix internal card width issue
Fix internal card width issue and replace question card to internal card

fix width issue in internal message card

---

app/details/[ticket_id]/ticketDetails.tsx

updated ticket detail tag background color
updated ticket detail tag background color

updated ticket detail tag background color

---

app/details/[ticket_id]/ticketDetails.tsx
app/details/style.tsx

Ticket details -> Handle reverse scroll
Handle reverse scroll

Origin/ticket details/handle reverse scroll

---

app/details/[ticket_id]/ticketDetails.tsx
helpers/common.tsx
stores/ticketStore.ts

Message - make message sent async
create message obj and set in mobX
https://share.teamcamp.app/rJtot7-Zg8LgTETLUBHR0

create message obj and set in mobX

---

app/setting/members/members.tsx
components/dropDown/dropDown.tsx
components/memberCard/memberCard.tsx
stores/workspaceStore.ts

members - invited users - delete working
invited users delete working

invited users - delete working

---

app/details/[ticket_id]/ticketDetails.tsx

Ticket details - hide three dots for now
commit three dot icon

Origin/ticket details/hide three dots for now

---

app/details/[ticket_id]/ticketDetails.tsx

Ticket details - priority - will update priority if it's different than current priority
add condition in onChangePriority
https://share.teamcamp.app/TO6WxMTNx9fCcLPqCxpzk

Origin/ticket/priority will update priority if it's different than current priority

---

services/clientSide/settingServices .ts

Setting - label - create service for delete label
create services for delete label

create services for delete label

---

services/clientSide/settingServices.ts

create service get all API key
create service get all API key
testing done.

create service get all API key

---

app/setting/apikey/apiKey.tsx
services/clientSide/settingServices.ts
stores/index.ts
stores/settingStore.ts
stores/workspaceStore.ts
utils/dataTypes.tsx

Setting - API Key dynamic list
Setting - API Key dynamic list
https://share.teamcamp.app/E1520ojDEq3wN5na0JEPX

Setting - API Key dynamic list

---

app/inbox/style.tsx
components/inboxCard/inboxCard.tsx
components/inboxCard/style.tsx

inbox screen feedback updated
inbox screen feedback updated

inbox screen feedback updated

---

app/details/[ticket_id]/ticketDetails.tsx
app/details/style.tsx
components/commentBox/style.tsx
components/internalMessageCard/style.tsx
components/messageCard/messageCard.tsx
components/messageCard/style.tsx
services/clientSide/settingServices.ts

Fix profile position issue and fix same design related isssue
Fix profile position issue and fix same design related issue in ticket details

Fix ticket details profile position issue

---

app/api/tickets/[ticketId]/messages/route.ts
helpers/emails.tsx
prisma/schema/enums.prisma
prisma/schema/schema.prisma
services/serverSide/workspace.ts
utils/dataTypes.tsx

Implemented workspace configuration table for maintaing general workspace config.
Implemented configuration schema for workspaces, to store general workspace meta data.
```
model Configuration {
id           String     @id @default(uuid())
workspace_id String
workspace    Workspace  @relation(fields: [workspace_id], references: [id])
type         ConfigType
extra        String?
value        Json
created_at   DateTime   @default(now())
updated_at   DateTime   @default(now()) @updatedAt
@@unique(name: "workspace_config_id", [workspace_id, type, extra])
}
```

implemented workspace config table

---

app/api/workspaces/apikeys/route.ts
middlewares/withAdminAuth.ts
middlewares/withApiAuth.ts
middlewares/withAuth.ts
middlewares/withWorkspaceAuth.ts
services/serverSide/workspace.ts

Implemented seperate API auth middleware to reduce blotware and now only Admin and owners can create the API keys

implemented seperate api auth middleware

---

components/commentBox/style.tsx
components/messageCard/style.tsx

Fix richtext ul and ol issue same as teamcamp
Fix richtext ul,ol  issue
https://share.teamcamp.app/GYxX-z2Hbttzid-yxIpbK

Fix richtext ul ol issue

---

app/setting/apikey/apiKey.tsx
components/apiKeyCard/apiKeyCard.tsx
package.json
services/clientSide/settingServices.ts
yarn.lock

make copy API key working
make copy API key working
https://share.teamcamp.app/CxdqxwcFnetpwKMAZAsmR

make copy API key working

---

app/setting/labels/labels.tsx
components/labelCard/labelCard.tsx
services/clientSide/settingServices.ts
stores/settingStore.ts

Settings - label - make list dynamic
create getLabels function and use it

create getLabels function and use it

---

app/selectworkspace/selectWorkspace.tsx
components/labelCard/labelCard.tsx

fixed the icon in label screen
fixed the icon in label screen

fixed the icon in label screen

---

helpers/appInitHelper.tsx

after workspace call service to load labels
after workspace call service to load labels
testing done.

after workspace call service to load labels

---

app/selectworkspace/selectWorkspace.tsx
app/selectworkspace/style.tsx

new workspace add redirect to onboarding page
new workspace add redirect to onboarding page
https://share.teamcamp.app/vft78WEDshkjnOLv2Rhov

new workspace add redirect to onboarding page

---

app/setting/labels/labels.tsx
components/dropDown/dropDown.tsx
components/labelCard/labelCard.tsx
components/modalComponent/labelModal.tsx
stores/settingStore.ts
utils/dataTypes.tsx

Settings - label - update label detail working
create updateLabel action and use updateLabelDetails service
(https://share.teamcamp.app/EmxBaGNAzJA1MxvuckSkP)

create updateLabel action and use updateLabelDetails service

---

services/clientSide/ticketServices.ts

Ticket Service - create service to add label in ticket
create service for add label in ticket

create service for add label in ticket

---

components/profileSection/aiBlock.tsx
components/profileSection/styles.tsx

Create design for generate reply by AI
Make design for generate reply by AI

Generate reply section design

---

services/clientSide/settingServices.ts
services/clientSide/ticketServices.ts
services/clientSide/userService.ts
services/clientSide/workspaceServices.ts

use message store instead of alert
use message store instead of alert
testing done

use message store instead of alert

---

app/inbox/inbox.tsx
stores/ticketStore.ts

Ticket - manage filtered list in mobx store instead of state
create inboxTicketList action and use it in inbox component

create inboxTicketList action and use it in inbox component

---

app/selectworkspace/selectWorkspace.tsx

Select organization inside observer
Select organization inside observer
testing done.

Select organization inside observer

---

next.config.mjs

Next config - make string mode to false for multiple time component render
Next config - make string mode to false for multiple time component render
Before changes
Now

Next config - make string mode to false for multiple time component render

---

app/inbox/inbox.tsx
app/inbox/page.tsx
app/page.tsx
app/tickets/page.tsx
components/navbar/navbar.tsx
components/navbar/navbarItem.tsx
global/constants.ts
stores/ticketStore.ts

all tickets page working
all tickets page working
https://share.teamcamp.app/fXuNF-4v5EVRIfaZB1pOa

all tickets page working

---

app/details/[ticket_id]/ticketDetails.tsx

Ticket details - make add or delete label working for ticket
create function handleTicketLabel

create function handleTicketLabel

---

components/dropDownWithTag/dropDownWithTag.tsx
components/tag/tag.tsx

inbox label give icon
inbox label give icon

inbox label give icon

---

app/inbox/inbox.tsx
app/unassigned/page.tsx
components/navbar/navbar.tsx

Unassigned page dynamic work
Unassigned page dynamic work
https://share.teamcamp.app/rOVTSITjpAMnegPiJA5Wj

Unassigned page dynamic work

---

app/tickets/labels/[label_id]/labelDetails.tsx
app/tickets/labels/[label_id]/page.tsx

Create route page for different labels ticket show
create tickets/labels/[label_id] route

create tickets/labels/[label_id] route

---

components/contextMenu/contextMenu.tsx

context menu label add and remove
context menu label add and remove
https://share.teamcamp.app/zNV59N-0ktdw0M9pZWblO

context menu label add and remove

---

app/api/tickets/[ticketId]/messages/emailEvents/route.ts
app/api/tickets/[ticketId]/messages/route.ts
app/api/webhooks/postmark/route.ts
prisma/schema/enums.prisma
prisma/schema/schema.prisma
services/serverSide/message.ts
utils/dataTypes.tsx
utils/webhookPayloadType.tsx

Implemented webhook and services for Email events.

implement webhooks and service for email events

---

services/clientSide/settingServices.ts

create service for add macros
create service for add macros
testing done.

create service for add macros

---

app/details/[ticket_id]/ticketDetails.tsx
components/dropDown/dropDown.tsx
components/dropDown/style.tsx
components/inboxCard/inboxCard.tsx
components/inboxCard/style.tsx
components/labelDropdown/labelDropdown.tsx
components/labelDropdown/style.tsx

Inbox - labels - make design for show multiple selected labels
Inbox - labels - make design for show multiple selected labels and create separate component for label drop down
https://share.teamcamp.app/xi0rV9ztCD2o5ZYibHkg4

Multiple selected label design

---

services/clientSide/settingServices.ts

create service for update macros
create service for update macros
testing done.

create service for update macros

---

app/api/macros/route.ts
lib/zod/macro.ts
services/serverSide/macro.ts

create API for creating a macro
create api for creating a macro

create api for create macro

---

services/clientSide/settingServices.ts

create service for delete macros
create service for delete macros
testing done.

create service for delete macros

---

services/clientSide/settingServices.ts

create services get macros
create services get macros
testing done.

create services get macros

---

components/modalComponent/macroModal.tsx
stores/settingStore.ts
utils/dataTypes.tsx

macros dynamic add working
macros dynamic add working
https://share.teamcamp.app/GrumhzIAsDhUpa6iO6-tC

macros dynamic add working

---

app/inbox/inbox.tsx
app/tickets/labels/[label_id]/labelDetails.tsx

Navbar - labels - show tickets based on label
set condition for label and use inbox component

set condition for label and use inbox component

---

helpers/raw.tsx

Ticket details - snooze - based on tomorrow and next week show dynamic day and date
update raw data for snoozeItem

update raw data for snoozeItem

---

app/details/[ticket_id]/ticketDetails.tsx

Ticket details - send comment - move clear comment value before api call
move clear comment value before api call

move clear comment value before api call

---

app/details/[ticket_id]/ticketDetails.tsx
components/dropDown/dropDown.tsx

ticket details show dynamic list of macros
ticket details show dynamic list of macros

ticket details show dynamic list of macros

---

components/commentBox/style.tsx

comment box mention menu arrow key working
comment box mention menu arrow key working
https://share.teamcamp.app/Kaygnr99Bb8bGjaCkBWUm

comment box mention menu arrow key working

---

components/inboxCard/inboxCard.tsx

ticket-label-add-or-remove-async
ticket-label-add-or-remove-async
https://share.teamcamp.app/lr_DvwE5m57hNc3Pe2KnI

ticket-label-add-or-remove-async

---

app/api/tickets/[ticketId]/changeStatus/route.ts
app/details/[ticket_id]/ticketDetails.tsx
components/dropDown/dropDown.tsx
components/snoozeDropdown/snoozeDropdown.tsx
helpers/raw.tsx
services/clientSide/ticketServices.ts
services/serverSide/ticket.ts
utils/appTypes.tsx

Ticket details - snooze - based on tomorrow and next week show dynamic day and date
create onChangeSnooze function use it

create onChangeSnooze function use it

---

app/setting/labels/labels.tsx
components/dropDown/dropDown.tsx
components/labelCard/labelCard.tsx
components/modalComponent/labelModal.tsx

dropdown component remove unused props
dropdown component remove unused props
testing done.

dropdown component remove unused props

---

app/api/workspaces/apikeys/[apiKey]/route.ts
services/serverSide/apiKey.ts

Implemented service and route to delete API key.
DELETE: `/api/apiKeys/{apiKey}`
Returns deleted Api key

implemented service and route to delete API key

---

components/modalComponent/macroModal.tsx

set loading when update and create marco
set loading when update and create marco
https://share.teamcamp.app/dyOmkcFnC6zt72ALb14n8

set loading when update and create marco

---

components/deleteModal/deleteModal.tsx
components/macroCard/macroCard.tsx

macros delete show loading
macros delete show loading
https://share.teamcamp.app/8lm5xDxcFewL9n9bectSY

macros delete show loading

---

components/appProvider/index.tsx
components/dropDown/style.tsx

Settings - on setting pages error or success message not show
Settings - on setting pages error or success message not show

fix alert message issue in setting

---

components/contextMenu/contextMenu.tsx

context menu  labels add or remove action async
context menu  labels add or remove action async
testing done.

context menu  labels add or remove action async

---

app/setting/channel/emailChannel.tsx
components/emailChannelCard/emailChannelCard.tsx

channels  handle input field change
channels  handle input field change
https://share.teamcamp.app/RtuBbycqJETmSWIl4jC70

channels  handle input field change

---

components/inboxCard/inboxCard.tsx

ticket when i click close icon then not redirect details
ticket when i click close icon then not redirect details
https://share.teamcamp.app/clrwCjlQzJWiUgrkPC9qY

ticket when i click close icon then not redirect details

---

app/inbox/inbox.tsx
components/datePicker/datePicker.tsx
components/snoozeDropdown/snoozeDropdown.tsx

Ticket - remove snooze used as status for ticket pass in payload or for filter
replace ticket status SNOOZE to OPEN

replace ticket status SNOOZE to OPEN

---

app/api/tickets/[ticketId]/changeAssignee/route.ts
app/api/tickets/[ticketId]/route.ts
lib/zod/ticket.ts

Made unassigned all working.
pass `null` as assignedUser in updateAssigne service.

made unassign all working

---

app/details/[ticket_id]/ticketDetails.tsx

ticket details marcos selection work
ticket details marcos selection work
https://share.teamcamp.app/4kcu3dyMbm15p4-9g8czt

ticket details marcos selection work

---

app/api/tickets/[ticketId]/changeAssignee/route.ts

Replaced session user id with emprty string in refrence, when unassigned to all

replaced session user id with empty string

---

app/details/[ticket_id]/ticketDetails.tsx

Ticket - unassign - show proper message when unassign ticket
add condition for unassigned ticket

add condition for unassigned ticket

---

services/clientSide/ticketServices.ts

Ticket - Create service for snooze ticket
create service for snooze ticket

create service for snooze ticket

---

app/details/[ticket_id]/ticketDetails.tsx

Ticket - when snooze ticket show proper message
add condition on display message

add condition on display message

---

components/navbar/navbar.tsx

Navbar - hide some item
Navbar - hide sidebar icon and 'Get Started' item

navbar - hide sidebar icon and 'Get started' item

---

app/details/[ticket_id]/ticketDetails.tsx

Ticket details - make this title for message dynamic
display contact name

display contact name

---

app/api/macros/route.ts
services/serverSide/ticket.ts

Implemented `last_message` field in tickets list.
`last_message` field includes author info and content of the message.

Implemented last message in ticket lists

---

app/details/[ticket_id]/ticketDetails.tsx

Ticket details - make close and re-open action async
add newMessage in ticket store

add newMessage in ticket store

---

components/inboxCard/inboxCard.tsx
utils/appTypes.tsx

Tickets - we will show here last message date instead of current date
display last update time on ticket

display last update time on ticket

---

services/clientSide/ticketServices.ts

Ticket details - when update priority or assignee page blink and details hide for some time
remove unrequired state form client side service
https://share.teamcamp.app/NEw5JgwjxQZ4euVQGfchh

remove unrequired state form client side service

---

services/clientSide/ticketServices.ts

Ticket services - remove unused service for update ticket details
remove unused service for update ticket details

remove unused service for update ticket details

---

components/datePicker/datePicker.tsx
components/datePicker/style.tsx
components/icon/icon.tsx
components/inboxCard/inboxCard.tsx
components/inboxCard/style.tsx

tickets -> show snooze drop down in click of snooze icon
Tickets -> show snooze drop down in click of snooze icon

tickets -> show snooze drop down in click of snooze icon

---

components/contextMenu/contextMenu.tsx
components/datePicker/datePicker.tsx
components/inboxCard/inboxCard.tsx
components/inboxCard/style.tsx

Ticket - review snooze functionality everywhere
update snooze functionality

update snooze functionality

---

app/api/workspaces/inviteUsers/[userId]/reinvite/route.ts
helpers/emails.tsx
services/serverSide/workspace.ts

Implemented service and API route to resend invitation emails.
POST: `/api/workspaces/{workspaceId}/inviteUsers/{userId}/reinvite`

implemented service and api route to resend email

---

components/inboxCard/inboxCard.tsx
components/inboxCard/style.tsx

created design for show description for ticket
created design for show description for ticket

created design for show description for ticket

---

app/inbox/inbox.tsx
components/inboxCard/inboxCard.tsx

Ticket - make description dynamic for ticket
make description dynamic for ticket

make description dynamic for ticket

---

services/serverSide/ticket.ts

Added `profile_url` in author deatils for ticket's list last message.

Fix author details in tickets last message

---

components/inboxCard/inboxCard.tsx
components/renderHtml/index.tsx

Tickets - will not show this spread message for ticket list
remove spread message for ticket list

remove spread message for ticket list

---

components/memberCard/memberCard.tsx
services/clientSide/workspaceServices.ts

Provide the option to resend the invite to pending user
add reinvite user functionality

add reinvite user functionality

---

app/api/webhooks/postmark/route.ts
package.json
yarn.lock

Changed Email event payload for outbound emails.
Now, Recivier's email ID is store in extra field in EmailEvents for OPEN & DELIVERED event.

Change email event payload for open and delivered event

---

components/deleteModal/deleteModal.tsx
components/dropDown/dropDown.tsx
components/labelCard/labelCard.tsx
components/macroCard/macroCard.tsx
components/memberCard/memberCard.tsx

Setting - members - show confirmation box for delete member
add deleteModel component and make it working

add deleteModel component and make it working

---

services/serverSide/message.ts

Implemented read_by field for each messages.
read_by field illustrates how many times the client has opened the email and at what times.

implemented ready by field for each message

---

components/dropDown/dropDown.tsx
services/clientSide/workspaceServices.ts

Setting - members - after click on any menu item menu will be close
add condition for onClose
https://share.teamcamp.app/2vKxUfTrynGRiM9-t1Mu0

add condition for onClose

---

components/memberCard/memberCard.tsx
stores/workspaceStore.ts

Settings - members - when delete user show loading on delete button
add loading on delete member button
(https://share.teamcamp.app/h4MSWvzJ0iBzU0sYxUjaB)

add loading on delete member button

---

app/details/[ticket_id]/ticketDetails.tsx
app/details/style.tsx
app/globals.css
components/dropDown/dropDown.tsx
components/messageCard/messageCard.tsx
components/messageCard/style.tsx
utils/dataTypes.tsx

Ticket details add seen option in email message
In ticket detail screen added seen option in email message over hover dropdown opens.

Ticket details add seen option in email message

---

app/api/tickets/[ticketId]/messages/route.ts

User's last seen for the ticket is updated when they post a message in the ticket.

update user last seen when posting message

---

components/dropDown/dropDown.tsx
components/dropDown/style.tsx
components/messageCard/messageCard.tsx

fixed the text overlay issue and date time display issue
In ticket detail  screen fixed the seen dropdown issue related date and time display and text overflow issue

fixed the text overlay issue and date time display issue

---

helpers/appInitHelper.tsx

Signup - after signup / login user not navigate to inbox screen
add return condition for redirect on index page
(https://share.teamcamp.app/CLPcZ4136Rx8UqeqESzPM)

add return condition for redirect on index page

---

components/navbar/profileDropdown.tsx

Show setting option if user is admin/owner
Show setting option if user is admin/owner

Show setting option if user is admin/owner

---

components/messageCard/messageCard.tsx
components/messageCard/style.tsx

fixed the position issue for seen dropdown
fixed the position issue for seen dropdown

Fix the seen dropdown position issue

---

components/apiKeyCard/apiKeyCard.tsx
helpers/appInitHelper.tsx
services/clientSide/settingServices.ts
stores/settingStore.ts

Setting - members - make delete API key working
make delete API key working
https://share.teamcamp.app/CAqDcMMmPLIIjhOdS4sZL

make delete API key working

---

components/messageCard/style.tsx

fixed the long text overflow issue in ticket details message
in ticket details fixed the text overflow issue in message

fixed the long text overflow issue in ticket details message

---

components/inboxCard/style.tsx
components/internalMessageCard/style.tsx

fixed the text overflow issue
fixed the text overflow issue

fixed the text overflow issue

---

components/renderHtml/index.tsx

Message last seen date/time showing wrong information
Remove event call from render data using regx replace
Now event for message not call

Email message render - remove event call for postmark event

---

app/setting/apikey/apiKey.tsx
components/apiKeyCard/apiKeyCard.tsx
components/modalComponent/createKeyModal.tsx

Setting - api key - fix loading issue for create or delete API key
fix loading issue for create/delete API key
https://share.teamcamp.app/0T58nFnkLr9ZX2jOM4z1c

fix loading issue for create/delete API key

---

app/details/[ticket_id]/ticketDetails.tsx

Ticket details - when click on manage macros navigate to
onclick manage macros navigate to macros setting
https://share.teamcamp.app/WwSfKFBv4GSyc60yEdhtN

onclick manage macros navigate to macros setting

---

components/navbar/profileDropdown.tsx
components/settingNavBar/settingNavBar.tsx
components/settingNavBar/style.tsx

Fix settings pages show condition for admin/owner
display setting page based on role

display setting page based on role

---

.env.example
helpers/common.tsx
lib/firebaseAdmin.ts
package.json
services/serverSide/firebaseServices.ts
yarn.lock

Implemented Firebase admin services to upload files and email attachments

implemented firebase admin services to upload files

---

app/api/webhooks/postmark/route.ts
services/serverSide/firebaseServices.ts
utils/webhookPayloadType.tsx

Implemented service to upload incoming postmark attachments
The attachements are uploaded to `tickets/{ticketId}/messages/{messageId}/attachments` path on firebase using firebase admin services.

Implement service to upload incoming attachments

---

services/serverSide/firebaseServices.ts
services/serverSide/message.ts
utils/dataTypes.tsx

Implemented service to get ticket messages attachments.
Now, while fetching ticket's messages, the attachments are fetched parrellely.

implemented service to get ticket messages attachments

---

app/api/tickets/[ticketId]/messages/route.ts
helpers/emails.tsx
services/serverSide/firebaseServices.ts
services/serverSide/message.ts
utils/dataTypes.tsx

Implemented service to download and append attachments to emails.
Attachments are downloaded from firebase using attachment token and then attachments are appended to emails that are sent.

Append attachments to email while sending

---

app/login/login.tsx
app/login/style.tsx
app/signup/signup.tsx
app/signup/style.tsx

Fix onboarding screen feedback
Fix onboarding screen feedback

fix onboarding screen feedback

---

app/api/webhooks/postmark/route.ts

Re-open ticket if closed when recieved email from contact

change ticket status to OPEN if CLOSED when recieved email

---

app/details/[ticket_id]/ticketDetails.tsx
helpers/common.tsx
stores/appStore.ts
stores/index.ts

Message - attach - when attach any file for that time show loading time
display loading when upload file
https://share.teamcamp.app/BQYqld0W0k11oo4tzxoTx

display loading when upload file

---

app/details/[ticket_id]/ticketDetails.tsx

Message - when send message also set attachment in mobx store if it's added in message
add attachments in mobX

add attachments in mobX

---

lib/openAi.ts
services/serverSide/ticketSummary.ts
utils/dataTypes.tsx

Connect AI -> Implement services to generate ticket summary & contact sentiments
create services for ticket summary and sentiment

create services for ticket summary and sentiment

---

lib/zod/ticket.ts
prisma/schema/enums.prisma
prisma/schema/schema.prisma
services/serverSide/message.ts
services/serverSide/ticket.ts

Implemented schema for Web channel for tickets and messages Schema

Implement schema for web channels

---

app/details/[ticket_id]/ticketDetails.tsx
app/details/style.tsx
components/fileCard/fileCard.tsx
components/fileCard/style.tsx
components/icon/icon.tsx
components/icon/style.tsx
components/internalMessageCard/internalMessageCard.tsx
components/internalMessageCard/style.tsx
styles/typography.tsx

Create design for internal message when attachment is there
Fix attachment design for internal message card

create attachment design for internal message card

---

app/api/tickets/[ticketId]/changeAssignee/route.ts
app/api/tickets/[ticketId]/changePriority/route.ts
app/api/tickets/[ticketId]/changeStatus/route.ts
app/api/tickets/[ticketId]/messages/route.ts
app/api/tickets/[ticketId]/snooze/route.ts
app/api/tickets/route.ts
app/api/webhooks/postmark/route.ts
lib/zod/ticket.ts
prisma/schema/enums.prisma
services/serverSide/contact.ts
services/serverSide/message.ts
services/serverSide/ticket.ts

Implemente API route to create tickets from WEB.
POST: `/api/tickets`
```json
{
"senderEmail": "The email of the sender",
"senderName": "The name of the sender", // optional
"subject": "The subject of the message", // optional
"message": "The message of the sender"
}
```

implemented API route to create tickets

---

app/api/tickets/[ticketId]/generateSummary/route.ts
services/serverSide/ticketSummary.ts

Connect AI -> Implement Route to generate ticket summary & contact sentiments
add route for generateSummary

add route for generateSummary

---

app/api/tickets/[ticketId]/messages/route.ts
helpers/emails.tsx

Modified post message route to handle web channel tickets

modified postMessage route to handle WEB channel

---

services/clientSide/ticketServices.ts
stores/ticketStore.ts
utils/dataTypes.tsx

Connect AI -> Implement Client side services for summary & sentiments
create ticketSummary service and set mobX

create ticketSummary service and set mobX

---

services/serverSide/notifications.ts

Implemented basic template of Notification Provider to manage & send notifications

implemented basic template for notification provider

---

components/profileSection/aiBlock.tsx
stores/ticketStore.ts

Connect AI -> Update UI everytime user opens the ticket
display ticketsummary on ticketDetails page

display ticketsummary on ticketDetails page

---

app/api/tickets/route.ts
lib/openAi.ts
services/serverSide/ticket.ts
services/serverSide/ticketSummary.ts

Ticket title are now generate with Connect AI if no subject is provided

Generate title for web ticket if subject not provided

---

app/details/[ticket_id]/ticketDetails.tsx

Update UI for message from WEB channel
display message based on channel type

display message based on channel type

---

.husky/pre-commit
app/api/tickets/route.ts
helpers/emails.tsx
prisma/schema/schema.prisma
services/serverSide/ticket.ts

Fixed mailId contraint issue for Web tickets

Fix mail contraint issue

---

prisma/schema/relations.prisma
prisma/schema/schema.prisma

Implemented schemas for message reactions

implemented schemas for message reactions

---

prisma/schema/relations.prisma
prisma/schema/schema.prisma
services/serverSide/message.ts

Implemeted reactMessage service to add reactions to a message
When a user reacts on a message, the current reaction is checked:
- If has current reaction then:
- new reaction matches current reaction then remove reaction
- otherwise update reaction
- if not then create a new reaction

Implement service for message reactions

---

app/api/messages/[messageId]/react/route.ts
lib/zod/message.ts
prisma/schema/relations.prisma
prisma/schema/schema.prisma
services/serverSide/message.ts

Implemented API route to react messages
POST: `/api/messages/{messageId}/react`
```json
{
"reaction": "smile"
}
```

Implement route to react messages

---

app/api/messages/[messageId]/react/route.ts
services/serverSide/message.ts
services/serverSide/notifications.ts

Implemented notification service to send reactions notifications

implemented notification service to send reaction notifications

---

app/api/messages/[messageId]/react/route.ts
services/serverSide/message.ts
services/serverSide/notifications.ts

Optimised and Modified getTicketMessage service to return message reactions

Modify get messages service to return reactions

---

app/api/messages/[messageId]/react/route.ts
app/api/tickets/[ticketId]/changeAssignee/route.ts
app/api/tickets/[ticketId]/messages/route.ts
app/api/webhooks/postmark/route.ts
services/serverSide/contact.ts
services/serverSide/notifications.ts

Improvied notification provider and fixed certain bug while geting contact info

improved notification provider

---

app/api/tickets/[ticketId]/messages/route.ts

Fixed read_by bugs for web channels

fixed read_by bug for web channels

---

app/details/[ticket_id]/ticketDetails.tsx
components/internalMessageCard/internalMessageCard.tsx
stores/ticketStore.ts

Update reaction when user clicks on emoji
Update reactions when user clicks on emoji

Update reactions when user clicks on emoji

---

components/internalMessageCard/internalMessageCard.tsx
components/internalMessageCard/style.tsx

fixed the internal message design  for ticket details
fixed the internal message design  for ticket details

fixed the internal message design  for ticket details

---

app/details/style.tsx
components/internalMessageCard/internalMessageCard.tsx
components/internalMessageCard/style.tsx

Ticket details -> Fix reaction seen drop down
Fix reaction seen drop down position issue

fix reaction seen drop down issue

---

prisma/schema/schema.prisma
services/serverSide/contact.ts
services/serverSide/ticket.ts

Updated Contact Schemas
Conacts are now bound to workspaces

updated contact schema and services

---

services/clientSide/ticketServices.ts

Connect AI -> Add config variable to enable/disable AI
make connectAI enable/disable

make-connectAI-enable/disable

---

app/inbox/inbox.tsx
components/overdueCard/overdueCard.tsx

Inbox - unassign card - on click of view tickets navigate user to unassigned tab
on click of view tickets navigate user to unassigned tab
https://share.teamcamp.app/I_nzei5-sHsOUlsfg02Gy

on click of view tickets navigate user to unassigned tab

---

lib/zod/common.ts
services/serverSide/ticket.ts

Fixed `last_updated` in get workspace tickets api

fixed last updated in ticket fetch

---

app/inbox/inbox.tsx
app/inbox/style.tsx
components/contactUsModal/style.tsx
components/contextMenu/style.tsx
components/inboxCard/inboxCard.tsx
components/inboxCard/style.tsx
components/inboxLoading/inboxLoading.tsx
components/inboxLoading/style.tsx
components/navbar/ResponsiveNavbar.tsx
components/navbar/navbar.tsx
components/navbar/style.tsx

Create responsive design for inbox screen
Make responsive design for inbox screen
https://share.teamcamp.app/Na6X5nLOuvotiZmgURMLL

Inbox responsive design

---

app/inbox/inbox.tsx
app/inbox/style.tsx
components/contactUsModal/style.tsx
components/contextMenu/style.tsx
components/inboxCard/inboxCard.tsx
components/inboxCard/style.tsx
components/inboxLoading/inboxLoading.tsx
components/inboxLoading/style.tsx
components/navbar/ResponsiveNavbar.tsx
components/navbar/navbar.tsx
components/navbar/style.tsx

Fix date picker position issue in inbox screen
Fix date picker position issue in inbox screen
https://share.teamcamp.app/ot5eYgCYI8TR02T7Cs-k_

Fix date picker position issue

---

app/details/[ticket_id]/ticketDetails.tsx
components/prosemirror/index.tsx
helpers/common.tsx

Prosemirror - Make file upload working
Prosemirror editor - add logic for embed image
https://share.teamcamp.app/L2QPaP7DkwODJEZO28uTt

Prosemirror editor - add logic for embed image

---

app/details/[ticket_id]/ticketDetails.tsx
app/details/style.tsx
app/globals.css

Fix design feedback in ticket details screen
Fix design feedback in ticket details screen

fix same design feedback

---

app/contact/companyList.tsx
app/contact/contact.tsx
app/contact/personList.tsx
app/contact/style.tsx
app/inbox/style.tsx
components/contactCard/contactCard.tsx
components/contactCard/style.tsx
components/contactsLoading/contactsLoading.tsx
components/contactsLoading/style.tsx

created loading state for contacts screen
created loading state for contacts screen

created loading state for contacts screen

---

components/prosemirror/index.tsx
global.d.ts

Prosemirror - implement mention functionality
Prosemirror - implement mention user functionality and also working search for user

Prosemirror - make mention functionality working

---

services/serverSide/notifications.ts

Updated mentioned user logic with prose-mirror

Update mention user logic with prose mirror

---

app/inbox/style.tsx
components/contactUsModal/contactUsModal.tsx
components/contactUsModal/style.tsx
components/navbar/ResponsiveNavbar.tsx
components/navbar/navbar.tsx
components/navbar/style.tsx

Create support modal responsive design
make responsive design for support modal

create support modal responsive design

---

services/serverSide/contact.ts
services/serverSide/firebaseServices.ts

Optimised contact & firebase attachment services

optimised firebase and contact queries

---

services/serverSide/ticket.ts

Optimised service to fetch workspace tickets and added comments

optimised service to fetch workspace tickets

---

app/inbox/inbox.tsx
components/notificationCard/notificationCard.tsx

fixed notification cad not display on default after enable

fixed notification cad not display on default after enable

---

app/globals.css
components/prosemirror/index.tsx

fixed the prosemirror style
fixed the prosemirror style

fixed the prosemirror style

---

app/details/[ticket_id]/ticketDetails.tsx
app/details/style.tsx
app/globals.css
components/prosemirror/index.tsx

Fix spacing in rich text input same as we have in figma
Fix spacing in rich text input same as we have in figma

Fix spacing in rich text input same as we have in figma

---

app/details/[ticket_id]/ticketDetails.tsx
app/details/style.tsx
app/globals.css
components/prosemirror/index.tsx

Reverts getconnect-tech/connect#421

Revert "Fix spacing in rich text input same as we have in figma"

---

components/prosemirror/index.tsx

Add placeholder text to prosmirror
Prosemirror - add placeholder text

Prosemirror - add placeholder text

---

prisma/schema/enums.prisma
prisma/schema/schema.prisma
services/serverSide/contact.ts

Updated Contact schemas with additional traits
renamed Company model with Group

updated contact schemas

---

app/details/style.tsx
app/globals.css

fixed the spacing around content
fixed the spacing around content

fixed the spacing around content

---

app/globals.css

added the font size and weight for prosemirror
added the font size and weight for prosemirror

added the font size and weight for prosemirror

---

app/globals.css

removed background
removed background from prosemirror css

removed background

---

components/internalMessageCard/internalMessageCard.tsx
components/messageCard/messageCard.tsx

added classname Prosemirror to every message
added classname Prosemirror to every message

added classname Prosemirror to every message

---

app/details/[ticket_id]/ticketDetails.tsx
components/macroCard/macroCard.tsx
components/modalComponent/macroModal.tsx
components/prosemirror/index.tsx
services/clientSide/settingServices.ts
stores/settingStore.ts

Settings - macros - use prosemirror editor instead of richtext component
replace richtext component with prosemirror
https://share.teamcamp.app/Hh99ZWJFS_rhDEYUqJeE3

replace richtext component with prosemirror

---

helpers/common.tsx
lib/zod/contact.ts
services/serverSide/contact.ts
utils/appTypes.tsx

Updated createOrUpdate contact service to support custom traits

updated create or update contact service

---

.vscode/settings.json
app/api/contacts/[contactId]/route.ts
helpers/errorHandler.ts
lib/zod/contact.ts
utils/appTypes.tsx

Implemented API route to update contact traits
PUT: `/api/contacts/{contactId}`
```json
{
"address": {
"street": "123 Main St",
"city": "Sample City",
"state": "Sample State",
"country": "Sample Country",
"postal_code": "12345"
},
"age": 30,
"avatar": "https://example.com/avatar.jpg",
"birthday": "1993-05-21T00:00:00Z",
"description": "This is a sample description about the contact.",
"firstName": "John",
"lastName": "Doe",
"name": "John Doe",
"gender": "MALE",
"phone": "1234567890",
"title": "Software Engineer",
"username": "johndoe123",
"website": "https://example.com",
"customTraits": {
"hobby": "coding",
"favoriteColor": "blue"
}
}
```

implemented API route to update contact traits

---

prisma/schema/relations.prisma
prisma/schema/schema.prisma
services/serverSide/contact.ts

Updated group and implemented contact-group relationship schema

updated group and relationship schemas

---

lib/zod/group.ts
prisma/schema/schema.prisma
services/serverSide/group.ts

Implemented service to create, update and get groups for a workspace

implemented service to create and update groups

---

components/contactUsModal/contactUsModal.tsx

Contact us - make this contact us modal working
use ProsemirrorEditor in contactUsModal

use ProsemirrorEditor in contactUsModal

---

app/api/contacts/[contactId]/route.ts
app/api/groups/[groupId]/route.ts
app/api/groups/route.ts
lib/zod/common.ts
prisma/schema/schema.prisma

Implemented external ID field for contact and schemas

implemented external id for contact and group

---

components/contactUsModal/contactUsModal.tsx
components/prosemirror/index.tsx

Fix buld error for prosemirror
Fix buld error for prosemirror - fix 
Works properly

Prosemirror - fix error for placeholder props

---

app/api/groups/[groupId]/addContacts/route.ts
app/api/groups/[groupId]/removeContacts/route.ts
app/api/groups/route.ts
lib/zod/contact.ts
services/serverSide/group.ts

Implemented API routes to add/remove contacts from groups.
POST: `/api/groups/{groupId}/addContacts`
Add multiple contacts to a group
```json
[
"contact_id_1",
"contact_id_2",
"contact_id_3"
]
```
POST: `/api/groups/{groupId}/removeContacts`
Remove multiple contacts to a group
```json
[
"contact_id_1",
"contact_id_2",
"contact_id_3"
]
```

implemented API routes to add/remove contacts from group

---

components/contactUsModal/contactUsModal.tsx
components/contactUsModal/style.tsx

fixed the prosemirror design in contact us
fixed the prosemirror design in contact us

fixed the prosemirror design in contact us

---

app/setting/myprofile/page.tsx
app/setting/style.tsx
components/navbar/style.tsx
components/profileSection/responsiveProfileSection.tsx
components/settingAppProvider/index.tsx
components/settingNavBar/responsiveSettingNavBar.tsx
components/settingNavBar/style.tsx

Create account screen responsive design
Create account screen responsive design

Create account screen responsive design

---

app/contact/style.tsx

added bottom spacing
In contact screen added bottom spacing

added bottom spacing

---

.eslintrc.json
components/contactUsModal/contactUsModal.tsx
helpers/common.tsx

Contact us - make attach file working and pass in payload
make attach file working
(https://share.teamcamp.app/gDIMp7KjEjf5HH3LP6j0w)

make attach file working

---

app/inbox/inbox.tsx

Inbox -> This should not count snoozed tickets!
fix count on overdueCard
https://share.teamcamp.app/aTUPdvaw_FfjpKz7Ub6oN

fix count on overdueCard

---

services/serverSide/contact.ts
services/serverSide/group.ts

Implemented contacts and ticket's open & close count in groups API.

Make group contacts, tickets' open & close dynamic

---

components/profileSection/profileSection.tsx
components/profileSection/responsiveProfileSection.tsx
components/profileSection/workDetails.tsx
services/clientSide/contactServices.ts
utils/dataTypes.tsx

ticket details -> make contact's group info dynamic
Make contact group info dynamic

Make contact group info dynamic

---

components/contactUsModal/contactUsModal.tsx
helpers/common.tsx

When upload attachments in Contact US, its also uploaded in message input and shows (NaN)
add condition in getFirebaseUrlFromFile function

add condition in getFirebaseUrlFromFile function

---

app/globals.css
components/internalMessageCard/style.tsx
components/messageCard/style.tsx

Ticket details -> fix overlay issue on emoji picker
Ticket details -> fix overlay issue on emoji picker
https://share.teamcamp.app/WVpKCkilXmAOiCwy49MkD

ticket details overlay issue on emoji picker

---

app/details/style.tsx
app/setting/apikey/apiKey.tsx
app/setting/style.tsx
components/apiKeyCard/apiKeyCard.tsx
components/apiKeyCard/style.tsx
components/apiKeyLoading/style.tsx
components/modalComponent/style.tsx

Create api key screen responsive design
Create api key screen responsive design

create api key screen responsive design

---

app/setting/labels/labels.tsx
app/setting/style.tsx
components/deleteModal/style.tsx
components/labelCard/labelCard.tsx
components/labelCard/style.tsx
components/labelIcoDropdown/style.tsx

Create label screen responsive design
Create label screen responsive design

Create label screen responsive design

---

app/details/[ticket_id]/ticketDetails.tsx

Fix useMediaQuery Error
Fix useMediaQuery Erroror

Fix useMediaQuery Error

---

app/setting/macros/macros.tsx
components/labelCard/labelCard.tsx
components/labelCard/style.tsx
components/macroCard/macroCard.tsx
components/macroCard/style.tsx
components/modalComponent/style.tsx

Create macros screen responsive design
Create macros screen responsive design

Create macros screen responsive design

---

app/api/contacts/[contactId]/refresh/route.ts
app/api/tickets/[ticketId]/messages/route.ts
prisma/schema/enums.prisma
prisma/schema/schema.prisma
services/serverSide/workspace.ts
utils/dataTypes.tsx

Updated Workspace Config schema and added support for webhooks.
Implemented contact refresh webhook which is called when contacts are refreshed, this webhook should update the contact details using update contact API and return status code 200.

Update workspace config and implement contact refresh webhook

---

app/contact/contact.tsx
app/contact/personList.tsx
app/contact/style.tsx
app/setting/members/members.tsx
app/setting/style.tsx
components/contactCard/style.tsx
components/memberLoading/memberLoading.tsx
components/memberLoading/style.tsx

Create loading state design in member screen
Create loading state design in member screen

Create member screen loading state

---

app/api/contacts/[contactId]/route.ts
app/details/[ticket_id]/ticketDetails.tsx
components/datePicker/datePicker.tsx
components/inboxCard/inboxCard.tsx
components/profileSection/profileSection.tsx
components/profileSection/recentEvent.tsx
components/profileSection/responsiveProfileSection.tsx
helpers/emails.tsx
services/clientSide/contactServices.ts
services/clientSide/ticketCacheServices.ts
services/serverSide/ticket.ts
stores/contactStore.ts
stores/ticketStore.ts
utils/appTypes.tsx
utils/dataTypes.tsx

Deatch contact object from ticket details
display contact information based on getContactDetailById service

Detach contact details from ticket details

---

app/api/contacts/[contactId]/refresh/route.ts
components/profileSection/profileSection.tsx
services/clientSide/contactServices.ts

Make refresh icon working
make working refresh button for contact information
https://share.teamcamp.app/IYYsTcT4x_NEroM3s9W90

Make contact refresh working

---

app/api/contacts/[contactId]/activites/route.ts
app/api/groups/[groupId]/route.ts
app/api/groups/route.ts
lib/zod/contact.ts
lib/zod/group.ts
services/serverSide/group.ts

fixed group data format

---

app/api/contacts/[contactId]/route.ts
app/contact/companyList.tsx
components/contactCard/contactCard.tsx
components/profileSection/profileSection.tsx
components/profileSection/responsiveProfileSection.tsx
components/profileSection/workDetails.tsx
lib/zod/contact.ts
services/serverSide/ticketSummary.ts

Update Contact's and Groups info on Connect UI
Update Contact's and Groups info on Connect UI

Update contact and groups info on connect UI

---

lib/zod/contact.ts

Fixed update contact payload schema

Fix create and update contact payload

---

components/prosemirror/index.tsx

Prosemirror - bullet point not work for multiple lines
Prosemirror - menu bar - bullet point button working for multiple lines also
https://share.teamcamp.app/T_tD8P7wQlo9P-_AkNs9l

Prosemirror - menubar - improve bullet point button

---

app/globals.css

Prosemirror - fix issue for mention
Prosemirror - mention fix issue for when mention user it's go to next line
https://share.teamcamp.app/ZG2iKL7q_OnJSDIhOIg6y

Prosemirror - fix on mention cursor go to next line

---

app/login/login.tsx
app/signup/signup.tsx
services/clientSide/authService.ts

When login it's not navigate to home screen
Login issue fix - clear local data when logout and set default routing for login and signup page

Fix login issue

---

app/login/login.tsx
app/signup/signup.tsx

Login - Fix navigation issue
Login - Fix navigation issue
Works properly

Login - Fix navigation issue

---

app/globals.css
components/profileSection/styles.tsx
components/prosemirror/index.tsx

fixed the menubar design and formatting
fixed the menubar design and formatting and added menu item onclick instead of hover.
fixed the position for menubar to open

fixed the menubar design and formatting

---

app/globals.css

added the box shadow to menu bar
added the box shadow to menu bar

added the box shadow to menu bar

---

components/appProvider/index.tsx

Fixed hooks update issue in safari mobile

fixed hooks update issue in safari

---

app/globals.css

added border in menu bar
added border in menu bar

added border in menu bar

---

app/api/auth/login/route.ts
app/api/auth/sendVerificationCode/route.ts
app/api/auth/signup/route.ts
lib/authOptions.ts
services/serverSide/workspace.ts

Normalised email field for login, signup and invite users

normalised email field for login signup and invite users

---

app/inbox/inbox.tsx
components/notificationCard/notificationCard.tsx
helpers/appInitHelper.tsx
helpers/common.tsx

Added utlity function to check if notifiations are supported

implemented utlitiy function to check if notifiations are supported

---

app/contact/companyList.tsx
app/inbox/inbox.tsx
services/clientSide/authService.ts

fix build error on contact and inbox page
update contact and inbox page

update contact and inbox page

---

app/details/[ticket_id]/ticketDetails.tsx

Fix built error in ticketDetails page
update ticketDetails page

update ticketDetails page

---

app/login/login.tsx
app/selectworkspace/selectWorkspace.tsx
app/signup/signup.tsx
services/clientSide/ticketServices.ts

Fix built error in login, signup and selectWorkspace page
update login signup and selectWorkspace page

update login signup and selectWorkspace page

---

components/profileSection/recentEvent.tsx
components/profileSection/styles.tsx

Added 'Show all' and 'Show less' label for recent event in ticket details 
Ticket Details -> Show only 5 recent event's and add "Show all" labels at end
Screen recording :- https://share.teamcamp.app/jIFbek-K5nhp9Bm6gbgXm

Added "Show all" and "Show less" for recent event

---

components/profileSection/eventStats.tsx

Added "Show all" And "Show less" label for events stats in ticket details 
Added "Show all" And "Show less" label for events stats in ticket details

added "Show all" and "Show less" label for events stats

---

.vscode/settings.json
app/api/teamcamp/project/users/route.ts
app/api/teamcamp/tasks/route.ts
lib/zod/teamcamp.ts
services/serverSide/teamcamp.ts
utils/dataTypes.tsx

Implemented APIs for Teamcamp tasks deatils
GET: `/api/teamcamp/tasks/`
Response: list of tasks
POST: `/api/teamcamp/tasks/`
Request Body:
```
{
taskName: string;
description: string;
priority: number;
taskUsers: string[];
files: { 
fileType: string; 
href: string; 
name: string; 
size: string 
}[];
}
```
GET: `/api/project/users`
Response: list of project users from teamcamp

Implemented Task APIs

---

.env.example
app/details/[ticket_id]/ticketDetails.tsx
components/profileSection/profileSection.tsx
components/profileSection/teamcampIntegration/createTaskModal.tsx
components/profileSection/teamcampIntegration/teamcampintegration.tsx
global/constants.ts
services/clientSide/teamcampService.ts
services/serverSide/serverAction.ts
services/serverSide/teamcamp.ts
stores/index.ts
stores/teamcampStore.ts
utils/dataTypes.tsx

Make Teamcamp section and Task modal dynamic
Make teamcamp section and task modal dynamic
https://share.teamcamp.app/QMSSM4k1O6lHWKuR8ZHb-

Make teamcamp section and task modal dynamic

---

app/api/teamcamp/tasks/createTask/route.ts
app/api/teamcamp/tasks/getTasks/route.ts
app/details/[ticket_id]/ticketDetails.tsx
components/profileSection/teamcampIntegration/createTaskModal.tsx
components/profileSection/teamcampIntegration/teamcampintegration.tsx
prisma/schema/schema.prisma
services/clientSide/teamcampService.ts
services/serverSide/teamcamp.ts
stores/teamcampStore.ts
utils/dataTypes.tsx

Store task_id in ticket.
modify service for getTask and create task
https://share.teamcamp.app/dms2KSlF3FN9MGzF8d_0h

Store teamcamp task id in ticket

---

components/profileSection/teamcampIntegration/createTaskModal.tsx

When i create task using API, Please add link read-only link to Connect ticket
add link on create task

add link on create task

---

components/profileSection/teamcampIntegration/teamcampintegration.tsx
components/prosemirror/index.tsx

When I click on a new task, copy the last message from the end user on task description, generate task title from ai
set title and description in create task model

generate task title and description

---

components/profileSection/teamcampIntegration/createTaskModal.tsx

Create task - when pass link data add label as ticket title for link
add label in create task link

add label in create task link

---

app/globals.css
app/setting/style.tsx
app/setting/workspaceprofile/timePickerSection.tsx
app/setting/workspaceprofile/workSpaceProfile.tsx
components/button/style.tsx
components/datePicker/datePicker.tsx
components/datePicker/style.tsx
package.json
yarn.lock

Created component for office hour.
Created component for office hour.
Added time picker.
Fixed width issue for antd trigger.

created design for office our

---

app/onboarding/onboarding.tsx
app/onboarding/style.tsx
app/setting/style.tsx
app/setting/workspaceprofile/workSpaceProfile.tsx
helpers/common.tsx

Added office hour field in onboarding page.
created design for office hour field in onboarding page.

created design for office hour in onboarding page

---

app/api/workspaces/settings/route.ts
app/setting/workspaceprofile/timePickerSection.tsx
app/setting/workspaceprofile/workSpaceProfile.tsx
services/clientSide/workspaceServices.ts

Make this working after API is update
make office data feature working

Darshan italiya/task 798/make this working after api is update

---

app/api/workspaces/settings/route.ts
app/onboarding/onboarding.tsx
app/setting/workspaceprofile/timePickerSection.tsx
app/setting/workspaceprofile/workSpaceProfile.tsx
services/clientSide/workspaceServices.ts
services/serverSide/workspace.ts
utils/dataTypes.tsx

make onboarding working
update backend and make wokring
https://share.teamcamp.app/dS8WWRbknXirA0ua4PGSx

Darshan italiya/task 800/onboarding backend add office hour field in a workspace

---

app/contact/[contactId]/contactDetail.tsx
app/contact/[contactId]/page.tsx
app/contact/[contactId]/style.tsx
app/contact/companyList.tsx
app/contact/personList.tsx
components/button/style.tsx
components/contactCard/contactCard.tsx
components/contextMenu/contextMenu.tsx
components/inboxCard/inboxCard.tsx
components/input/input.tsx
components/profileSection/workDetails.tsx
doc/README.md
doc/api/README.md
doc/architecture.md
doc/authentication.md
doc/database-schema.md
doc/getting-started.md
doc/project-overview.md
doc/pull_request_template.md
helpers/common.tsx
services/clientSide/contactServices.ts
stores/contactStore.ts
utils/dataTypes.ts

Create a doc related to existing system

Create a doc

---

doc/README.md
doc/api/README.md
doc/architecture.md
doc/authentication.md
doc/database-schema.md
doc/getting-started.md
doc/project-overview.md
doc/pull_request_template.md

Add a document related all module

add doc for existing system

---

app/api/contacts/[contactId]/route.ts
services/serverSide/contact.ts

Create API For get Contact Detail
create api for get contact detail
API for Contact Tickets and Contact Details

Darshan italiya/task 811/create api for get contact detail

---

components/profileSection/recentEvent.tsx

https://dash.teamcamp.app/projects/details/80-FazB5Bc-oKUuAZKRA5/tasks?&task=xNvqX62O1fia_U52Sa4BI
Changed empty state text for recent event.
Changed empty state text for recent event.

changed text

---

app/api/groups/[groupId]/route.ts
doc/api/README.md
services/serverSide/group.ts

Create API for get group Detail same as contact detail
create api for get group details

create api for get group details

---

components/inboxCard/style.tsx

Added font style italic for awaiting text in inbox card.
Added font style italic for awaiting text in inbox card.

added font style

---

app/company/[company_id]/companyDetails.tsx
app/company/[company_id]/page.tsx
app/company/[company_id]/style.tsx
app/contact/[contact_id]/detailsSection.tsx
app/contact/companyList.tsx
app/contact/contact.tsx
app/contact/style.tsx
components/contactCard/contactCard.tsx
components/contactCard/style.tsx

https://dash.teamcamp.app/projects/details/80-FazB5Bc-oKUuAZKRA5/tasks?&task=aHsxDHBs9eKyIraZYxhtb
Created design for workspace details screen.
Created new page for workspace details screen. Page route is /company/[company_id]. And This company id is workspace card id.
And clicked on workspace card than redirect in workspace details page.
Added hover color for contact card.
Changed hover color for workspace toggle.
Added condition for contact details screen and workspace details screen.

updated props

---

components/renderHtml/index.tsx

[Ticket Detail] ticket detail not open
update RenderHtml

fix ticket data display issue

---

app/company/[company_id]/companyDetails.tsx
app/company/[company_id]/page.tsx
helpers/common.tsx
services/clientSide/contactServices.ts
stores/contactStore.ts
utils/dataTypes.tsx

Make Group detail page dynamic
make group detail page dynamic

Darshan italiya/task 820/make group detail page dynamic

---

app/company/[company_id]/companyDetails.tsx
app/contact/[contact_id]/contactDetail.tsx

Currently in contact detail and company detail page ticket filter not working . this changes fix this issue
create a ticket filter function and  and used filter data in render function
erified this is working . See screenshots  below.
show open tickets
empaty state
done tickets

make ticket filter working in contact and company detail

---

app/company/[company_id]/companyDetails.tsx
app/contact/[contact_id]/contactDetail.tsx

remove unused import and fix snoozed ticket logic
remove unused import form contactDetail.ts page

remove unused import

---

app/api/insights/resolution-time/route.ts
package.json
services/serverSide/report.ts
yarn.lock

Create api for median Resolution Time
Median resolution time - The typical time it takes for you to resolve your customer's request. Using the median minimizes bias from unusually fast or slow replies.
How to calculate:-
✅ Find closed tickets
✅ Calculate resolution time (cloased_at - created_at) for each ticket
✅ Sort resolution times per day and find the median

Varship/task 825/create api for median resolution time

---

app/company/[company_id]/companyDetails.tsx
services/serverSide/group.ts

[Contact Detail]on click group open group detail page
make contact clickble
https://share.teamcamp.app/uDITGgKpnn2cFouFd-OD0

Darshan italiya/task 826/contact detail on click group open group detail page

---

app/contact/[contact_id]/contactDetail.tsx
services/serverSide/group.ts

[Group Detail]Make contact card is clickble
make Group card clickble
https://share.teamcamp.app/jWehfQC9pU1ijYeFsQtXv

Darshan italiya/task 827/group detail make contact card is clickble

---

app/api/insights/first-response-time/route.ts
app/api/insights/queue-size/route.ts
app/api/insights/resolution-time/route.ts
package.json
services/serverSide/insights.ts
yarn.lock

Create api for median Resolution Time and  median first response report
create api for median first response report workspace wise
Median resolution time - The typical time it takes for you to resolve your customer's request. Using the median minimizes bias from unusually fast or slow replies.
How to calculate:-
✅ Find closed tickets
✅ Calculate resolution time (cloased_at - created_at) for each ticket
✅ Sort resolution times per day and find the median

create api for overview report

---

app/globals.css
assets/icons/SVGIcon.tsx
components/tiptapEditor/index.tsx

Tiptap - bubble menu - set design according to figma
Updated design for bubble menu

Laxita rajpurohit/task 831/tiptap bubble menu set design according to figmaa

---

app/globals.css

Tiptap editor - show proper placeholder
Showed the placeholder

Laxita rajpurohit/task 836/tiptap editor show proper placeholder

---

app/login/login.tsx
app/signup/signup.tsx

Login, signup & OTP enter - set auto focus on input
set auto focus on login signup otp page
https://share.teamcamp.app/nbAz-C9r8b3ckL1ZdpRFv

set auto focus on login signup otp page

---

app/globals.css
components/tiptapEditor/mentionList.tsx
components/tiptapEditor/style.tsx
components/tiptapEditor/suggestion.tsx

Tiptap editor - fix proper design for mention users
updated the mention user dropdown design

updated the mention user dropdown design

---

components/tiptapEditor/index.tsx
components/tiptapEditor/slashCommand/command.tsx
components/tiptapEditor/slashCommand/commandList.tsx
components/tiptapEditor/slashCommand/style.tsx
components/tiptapEditor/slashCommand/suggestion.tsx

Tiptap editor - slash commands menu show
added slash menu dropdown for tiptap and updated design for it with working

Laxita rajpurohit/task 842/tiptap editor slash commands menu show

---

components/tiptapEditor/mentionList.tsx
components/tiptapEditor/style.tsx

Tiptap editor - improve mention users working
fixed the scrolling issue when key arrow works for mention

fixed the scrolling issue when key arrow works for mention

---

app/globals.css
components/internalMessageCard/internalMessageCard.tsx
components/messageCard/messageCard.tsx

Tiptap editor - make table functionality working
created table functionality working and added style for tiptap table

Laxita rajpurohit/task 846/tiptap editor make table functionality workin

---

app/insights/insights.tsx
components/graphChart/chart.tsx
components/graphChart/style.tsx
components/insightsLoading/insightsLoading.tsx
components/insightsLoading/style.tsx

https://dash.teamcamp.app/projects/details/80-FazB5Bc-oKUuAZKRA5/tasks?&task=tf35ZcDMo-ndtQ7yWHRQp
Created design for loading state in analytics screen.
Created design for loading state in analytics screen.
Removed inline style for chart component.
Fixed hover border color for date picker.

fixed hover border color for date picker

---

app/details/[ticket_id]/ticketDetails.tsx
components/tiptapEditor/codeBlock/index.tsx
components/tiptapEditor/codeBlock/lowlight.ts
components/tiptapEditor/index.tsx

Tiptap editor - fix remaining functionality for bubble menu and slash menu
tiptap editor fix remaining functionality for bubble menu and slash menu
https://share.teamcamp.app/FNWpDZVRG_9bHJChD4ofH

Darshan italiya/task 850/tiptap editor fix remaining functionality for bubble menu and slash menu

---

app/insights/insights.tsx

[Insights]Fetch data based on dropdown
fetch data based on dropdown

Darshan italiya/task 853/insights fetch data based on dropdown

---

app/insights/insights.tsx
components/graphChart/chart.tsx

[Insights]Date should same that we fetch from api
pass date in chart componet and display it

pass date in chart componet and display it

---

app/details/[ticket_id]/ticketDetails.tsx
app/details/style.tsx

https://dash.teamcamp.app/projects/details/80-FazB5Bc-oKUuAZKRA5/tasks?&task=4b6c2TirfEZP0hdkzebUa
Fixed scrolling issue for ticket details right side.
Fixed scrolling issue for ticket details right side.
Calculated height for top section.
Screen recording :- https://share.teamcamp.app/s7WmEqSEGOFkPN7pN5lfi

fixed scrolling isse

---

components/navbar/navbar.tsx

[Navbar]Documents link opens the Contact Us modal
redirect on document click
https://share.teamcamp.app/V54brMmGLhQQAbPlfE1K2

Navbar/Support - redirect on document click

---

app/api/tickets/route.ts
app/api/webhooks/postmark/route.ts
services/serverSide/notifications.ts

Broadcast notifications to all workspace users on new ticket

broadcast notification to all users on new ticket
